
trigger:
  - none
  
name: Azure Pipelines

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureServiceConnectionId: 'bf16207c-0192-48bf-96d5-04c4a6350a49'
  subscription_id: '032f2e80-b6ef-44c4-93d4-6feb62c932cf'
  # Environment name
  environmentName: 'final-udacity-project-dennis'
stages:
- stage: deploy_terraform
  displayName: Deploy Terraform
  jobs: 
  - deployment: deploy_terraform
    continueOnError: false
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - task: TerraformInstaller@0
              displayName: 'install terraform'
              inputs:
                terraformVersion: 'latest'
            - task: Bash@3
              displayName: init
              inputs:
                targetType: 'inline'
                script: |
                  terraform init \
                  -backend-config="storage_account_name=dennistfstorageaccount" \
                  -backend-config="container_name=$dennistfcontainer" \
                  -backend-config="key=project.tfstate" \
                  -backend-config="access-key=$TF_STATE_BLOB_SAS_TOKEN"
                workingDirectory: $(System.DefaultWorkingDirectory)/terraform'
              env:
                TF_STATE_BLOB_ACCESS_KEY: $(access-key)
          
