
trigger:
  - none
  
name: Azure Pipelines

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureServiceConnectionId: 'bf16207c-0192-48bf-96d5-04c4a6350a49'
  subscription_id: '032f2e80-b6ef-44c4-93d4-6feb62c932cf'

  # Environment name
  environmentName: 'final-udacity-project-dennis'
stages:
- stage: deploy_terraform
  displayName: Deploy Terraform
  jobs: 
  - deployment: deploy_terraform
    continueOnError: false
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - task: TerraformInstaller@0
              displayName: 'install terraform'
              inputs:
                terraformVersion: 'latest'
            - task: AzureCLI@2
              inputs:
                azureSubscription: 'azure connection'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: 'az login --service-principal --username $(SERVICE-PRINCIPAL-NAME) --password  $(SERVICE-PRINCIPAL-KEY)  --tenant $(TENANT)'
            - task: TerraformTaskV3@3
              displayName: init
              inputs:
                provider: 'azurerm'
                command: 'init'
                backendServiceArm: 'azure connection'
                backendAzureRmResourceGroupName: 'udacity-resources'
                backendAzureRmStorageAccountName: 'dennistfstorageaccount'
                backendAzureRmContainerName: 'dennistfcontainer'
                backendAzureRmKey: 'terraform.tfstate'
                workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
            - task: TerraformTaskV3@3
              displayName: plan
              inputs:
                provider: 'azurerm'
                command: 'plan'
                environmentServiceNameAzureRM: 'azure connection'
                workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'

            - task: TerraformTaskV3@3
              displayName: apply
              inputs:
                provider: 'azurerm'
                command: 'apply'
                environmentServiceNameAzureRM: 'azure connection'
                workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'